// Code generated by fabricator-generate-api-go
//
// Modifications in code regions will be lost during regeneration!
package wombat_v2

// region CODE_REGION(GEN)
//go:generate protoc -I . v2_common.proto --go_out=module=example.com/api/wombat/v2/go/wombat_v2_common:./go/wombat_v2_common --blaze_out=module=example.com/api/wombat/v2/go/wombat_v2_common:./go/wombat_v2_common

//go:generate protoc -I . v2_player_service.proto --go_out=module=example.com/api/wombat/v2/go/wombat_v2_player:./go/wombat_v2_player --blaze_out=module=example.com/api/wombat/v2/go/wombat_v2_player:./go/wombat_v2_player

// endregion
