// Code generated by fabricator-generate-api-go
//
// Modifications in code regions will be lost during regeneration!
package wombat_v2_test

import (
	. "github.com/onsi/ginkgo/v2"
	_ "github.com/onsi/gomega"
)

var _ = Describe("Wombat", func() {

})
