// Code generated by fabricator-generate-api-go
//
// Modifications in code regions will be lost during regeneration!
package wombat_v2_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"testing"
)

func TestWombat(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Wombat Suite")
}
