// Code generated by protoc-gen-blaze. DO NOT EDIT.
// versions:
// 	blaze-gen-go v0.7.2
// 	protoc        v5.29.1
// source: v1_s2s_service.proto

package wombat_v1_s2s

import (
	blaze "code.cestus.io/blaze"
	context "context"
	wombat_v1_common "example.com/api/wombat/v1/go/wombat_v1_common"
)

// ===============================
// S2SWombat sample implementation
// ===============================

type s2SWombatServiceSample struct {
}

// Methods.
func (api *s2SWombatServiceSample) Echo(context.Context, *wombat_v1_common.EchoMessage) (*wombat_v1_common.EchoMessage, error) {
	return nil, blaze.ErrorUnimplemented("")
}
