// Code generated by fabricator-generate-api-go
//
// Modifications in code regions will be lost during regeneration!
package wombat_v1

// region CODE_REGION(GEN)
//go:generate protoc -I . v1_common.proto --go_out=module=example.com/api/wombat/v1/go/wombat_v1_common:./go/wombat_v1_common --blaze_out=module=example.com/api/wombat/v1/go/wombat_v1_common:./go/wombat_v1_common

//go:generate protoc -I . v1_player_service.proto --go_out=module=example.com/api/wombat/v1/go/wombat_v1_player:./go/wombat_v1_player --blaze_out=module=example.com/api/wombat/v1/go/wombat_v1_player:./go/wombat_v1_player

//go:generate protoc -I . v1_s2s_service.proto --go_out=module=example.com/api/wombat/v1/go/wombat_v1_s2s:./go/wombat_v1_s2s --blaze_out=module=example.com/api/wombat/v1/go/wombat_v1_s2s:./go/wombat_v1_s2s

//go:generate protoc -I . v1_admin_service.proto --go_out=module=example.com/api/wombat/v1/go/wombat_v1_admin:./go/wombat_v1_admin --blaze_out=module=example.com/api/wombat/v1/go/wombat_v1_admin:./go/wombat_v1_admin

//go:generate protoc -I . v1_public_service.proto --go_out=module=example.com/api/wombat/v1/go/wombat_v1_public:./go/wombat_v1_public --blaze_out=module=example.com/api/wombat/v1/go/wombat_v1_public:./go/wombat_v1_public

// endregion
