// Code generated by fabricator-generate-plugin-go
//
// Modifications in code regions will be lost during regeneration!

package fabricatorgenerateservicego_test

import (
	"os"

	fabricatorgenerateapigo "code.cestus.io/tools/fabricator-generate-api-go/pkg/fabricator-generate-api-go"
	fabricatorgenerateservicego "code.cestus.io/tools/fabricator-generate-service-go/pkg/fabricator-generate-service-go"
	fabricatorgeneratetoolgo "code.cestus.io/tools/fabricator-generate-tool-go/pkg/fabricator-generate-tool-go"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Config", func() {
	It("Deserializes a fabricator config", func() {
		file, err := os.Open("./testdata/deserialize.yml")
		Expect(err).ToNot(HaveOccurred())
		config, err := fabricatorgenerateservicego.LoadPluginConfig(file)
		Expect(err).ToNot(HaveOccurred())
		expected := fabricatorgenerateservicego.PluginConfig{
			ApiVersion: "fabricator.cestus.io/v1alpha1",
			Kind:       "Config",
			Components: []fabricatorgenerateservicego.PluginComponent{
				{
					Name:      "fabricator-generate-service-go",
					Generator: "fabricator-generate-service-go",
					Spec: fabricatorgenerateservicego.Spec{
						PinDependency:         nil,
						ReplaceDependency:     nil,
						ToolDependency:        nil,
						ToolName:              "wombat",
						HasRelationalDatabase: true,
						APIs: []fabricatorgenerateservicego.API{
							{
								ServiceName: "wombat",
								GoModule:    "example.com/api/wombat",
								Kind:        fabricatorgenerateapigo.Admin,
								Version:     "v1",
								ReplaceDependency: fabricatorgenerateservicego.ReplaceDependencies{
									"example.com/api/wombat": fabricatorgenerateservicego.ReplaceDependency{
										Name: "example.com/api/wombat",
										With: "../api/wombat",
									},
								},
							},
							{
								ServiceName: "wombat",
								GoModule:    "example.com/api/wombat",
								Kind:        fabricatorgenerateapigo.Player,
								Version:     "v1",
								ReplaceDependency: fabricatorgenerateservicego.ReplaceDependencies{
									"example.com/api/wombat": fabricatorgenerateservicego.ReplaceDependency{
										Name: "example.com/api/wombat",
										With: "../api/wombat",
									},
								},
							},
							{
								ServiceName: "wombat",
								GoModule:    "example.com/api/wombat/v2",
								Kind:        fabricatorgenerateapigo.Player,
								Version:     "v2",
								ReplaceDependency: fabricatorgenerateservicego.ReplaceDependencies{
									"example.com/api/wombat/v2": fabricatorgenerateservicego.ReplaceDependency{
										Name: "example.com/api/wombat/v2",
										With: "../api/wombat/v2",
									},
								},
							},
							{
								ServiceName: "wombat",
								GoModule:    "example.com/api/wombat",
								Kind:        fabricatorgenerateapigo.Public,
								Version:     "v1",
								ReplaceDependency: fabricatorgenerateservicego.ReplaceDependencies{
									"example.com/api/wombat": fabricatorgenerateservicego.ReplaceDependency{
										Name: "example.com/api/wombat",
										With: "../api/wombat",
									},
								},
							},
							{
								ServiceName: "wombat",
								GoModule:    "example.com/api/wombat",
								Kind:        fabricatorgenerateapigo.S2S,
								Version:     "v1",
								ReplaceDependency: fabricatorgenerateservicego.ReplaceDependencies{
									"example.com/api/wombat": fabricatorgenerateservicego.ReplaceDependency{
										Name: "example.com/api/wombat",
										With: "../api/wombat",
									},
								},
							},
						},
						Commands: []fabricatorgeneratetoolgo.Command{
							{
								Name: "ls",
								Flags: []fabricatorgeneratetoolgo.Flag{
									{
										Name:    "all",
										Type:    "bool",
										Default: "false",
										Usage:   "set to true",
									},
								},
							},
						},
					},
				},
			},
		}
		Expect(config).To(Equal(expected))
	})
})
