// Code generated by protoc-gen-blaze. DO NOT EDIT.
// versions:
// 	blaze-gen-go v0.7.2
// 	protoc        v5.29.1
// source: v2_player_service.proto

package wombat_v2_player

import (
	blaze "code.cestus.io/blaze"
	context "context"
	wombat_v2_common "example.com/api/wombat/v2/go/wombat_v2_common"
)

// ==================================
// PlayerWombat sample implementation
// ==================================

type playerWombatServiceSample struct {
}

// Methods.
func (api *playerWombatServiceSample) Echo(context.Context, *wombat_v2_common.EchoMessage) (*wombat_v2_common.EchoMessage, error) {
	return nil, blaze.ErrorUnimplemented("")
}
