// Code generated by protoc-gen-blaze. DO NOT EDIT.
// versions:
// 	blaze-gen-go v0.7.2
// 	protoc        v5.29.1
// source: v1_public_service.proto

package wombat_v1_public

import (
	bytes "bytes"
	blaze "code.cestus.io/blaze"
	blazetrace "code.cestus.io/blaze/pkg/blazetrace"
	context "context"
	wombat_v1_common "example.com/api/wombat/v1/go/wombat_v1_common"
	fmt "fmt"
	v5 "github.com/go-chi/chi/v5"
	logr "github.com/go-logr/logr"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	http "net/http"
	strconv "strconv"
	strings "strings"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ======================
// PublicWombat Interface
// ======================

// PublicWombat is a Public Wombat
type PublicWombat interface {
	Echo(context.Context, *wombat_v1_common.EchoMessage) (*wombat_v1_common.EchoMessage, error)
}

// ============================
// PublicWombat Protobuf Client
// ============================

type publicWombatProtobufClient struct {
	client blaze.HTTPClient
	urls   [1]string
	opts   blaze.ClientOptions
	trace  blazetrace.ClientTracer
}

// NewPublicWombatProtobufClient creates a Protobuf client that implements the PublicWombat interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPublicWombatProtobufClient(addr string, client blaze.HTTPClient, opts ...blaze.ClientOption) PublicWombat {
	if c, ok := client.(*http.Client); ok {
		client = blaze.WithoutRedirects(c)
	}

	clientOpts := blaze.ClientOptions{
		Trace: blazetrace.NewClientTracer(),
	}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := blaze.UrlBase(addr) + PublicWombatPathPrefix
	urls := [1]string{
		prefix + "/" + "Echo",
	}

	return &publicWombatProtobufClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
		trace:  clientOpts.Trace,
	}
}

func (s *publicWombatProtobufClient) Echo(ctx context.Context, in *wombat_v1_common.EchoMessage) (*wombat_v1_common.EchoMessage, error) {
	ctx, span := s.trace.StartSpan(ctx, "Echo", blazetrace.WithAttributes(blazetrace.ClientName.String("PublicWombat")))
	ctx = s.trace.AnnotateWithClientTrace(ctx)
	defer s.trace.EndSpan(span)
	out := new(wombat_v1_common.EchoMessage)
	err := s.doProtobufRequest(ctx, s.client, s.urls[0], in, out)
	if err != nil {
		blerr, ok := err.(blaze.Error)
		if !ok {
			blerr = blaze.ErrorInternalWith(err, "")
		}
		span.SetStatus(blaze.OtelCodeFromErrorType(blerr), blerr.Error())
		return nil, blerr
	}
	span.SetStatus(blaze.OtelCodeFromErrorType(nil), "")
	return out, nil
}

// doProtobufRequest makes a Protobuf request to the remote Blaze service.
func (s *publicWombatProtobufClient) doProtobufRequest(ctx context.Context, client blaze.HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return blaze.ErrorInternalWith(err, "failed to marshal proto request")
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}

	req, err := blaze.NewHTTPRequest(ctx, url, reqBody, "application/protobuf", "v0.7.2")
	if err != nil {
		return blaze.ErrorInternalWith(err, "could not build request")
	}

	resp, err := client.Do(req)
	if err != nil {
		return blaze.ErrorInternalWith(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = blaze.ErrorInternalWith(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return blaze.ErrorFromResponse(resp)
	}

	respBodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return blaze.ErrorInternalWith(err, "failed to read response body")
	}
	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return blaze.ErrorInternalWith(err, "failed to unmarshal proto response")
	}
	return nil
}

// ========================
// PublicWombat JSON Client
// ========================

type publicWombatJSONClient struct {
	client blaze.HTTPClient
	urls   [1]string
	opts   blaze.ClientOptions
	trace  blazetrace.ClientTracer
}

// NewPublicWombatJSONClient creates a JSON client that implements the PublicWombat interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPublicWombatJSONClient(addr string, client blaze.HTTPClient, opts ...blaze.ClientOption) PublicWombat {
	if c, ok := client.(*http.Client); ok {
		client = blaze.WithoutRedirects(c)
	}

	clientOpts := blaze.ClientOptions{
		Trace: blazetrace.NewClientTracer(),
	}
	for _, o := range opts {
		o(&clientOpts)
	}

	prefix := blaze.UrlBase(addr) + PublicWombatPathPrefix
	urls := [1]string{
		prefix + "/" + "Echo",
	}

	return &publicWombatJSONClient{
		client: client,
		urls:   urls,
		opts:   clientOpts,
		trace:  clientOpts.Trace,
	}
}

func (s *publicWombatJSONClient) Echo(ctx context.Context, in *wombat_v1_common.EchoMessage) (*wombat_v1_common.EchoMessage, error) {
	ctx, span := s.trace.StartSpan(ctx, "Echo", blazetrace.WithAttributes(blazetrace.ClientName.String("PublicWombat")))
	ctx = s.trace.AnnotateWithClientTrace(ctx)
	defer s.trace.EndSpan(span)
	out := new(wombat_v1_common.EchoMessage)
	err := s.doJSONRequest(ctx, s.client, s.urls[0], in, out)
	if err != nil {
		blerr, ok := err.(blaze.Error)
		if !ok {
			blerr = blaze.ErrorInternalWith(err, "")
		}
		span.SetStatus(blaze.OtelCodeFromErrorType(blerr), blerr.Error())
		return nil, blerr
	}
	span.SetStatus(blaze.OtelCodeFromErrorType(nil), "")
	return out, nil
}

// doJSONRequest makes a JSON request to the remote Blaze service.
func (s *publicWombatJSONClient) doJSONRequest(ctx context.Context, client blaze.HTTPClient, url string, in, out proto.Message) (err error) {
	var buf []byte
	marshaler := &protojson.MarshalOptions{UseProtoNames: true}
	if buf, err = marshaler.Marshal(in); err != nil {
		return blaze.ErrorInternalWith(err, "failed to marshal json request")
	}
	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}

	req, err := blaze.NewHTTPRequest(ctx, url, bytes.NewReader(buf), "application/json", "v0.7.2")
	if err != nil {
		return blaze.ErrorInternalWith(err, "could not build request")
	}

	resp, err := client.Do(req)
	if err != nil {
		return blaze.ErrorInternalWith(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = blaze.ErrorInternalWith(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return blaze.ErrorFromResponse(resp)
	}

	respByte, err := io.ReadAll(resp.Body)
	if err != nil {
		return blaze.ErrorInternalWith(err, "failed to read response body")
	}
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(respByte, out); err != nil {
		return blaze.ErrorInternalWith(err, "failed to unmarshal json response")
	}
	if err = ctx.Err(); err != nil {
		return blaze.ErrorInternalWith(err, "aborted because context was done")
	}
	return nil
}

// ====================
// PublicWombat Service
// ====================

type publicWombatService struct {
	PublicWombat
	log            logr.Logger
	mux            *v5.Mux
	mountPath      string
	serviceTracer  blazetrace.ServiceTracer
	serviceOptions blaze.ServiceOptions
}

func NewPublicWombatService(svc PublicWombat, log logr.Logger, opts ...blaze.ServiceOption) blaze.Service {
	serviceOptions := blaze.ServiceOptions{
		Trace: blazetrace.NewServiceTracer(),
	}
	for _, o := range opts {
		o(&serviceOptions)
	}
	var r *v5.Mux
	if serviceOptions.Mux != nil {
		r = serviceOptions.Mux
	} else {
		r = v5.NewRouter()
	}

	service := publicWombatService{
		log:            log,
		mux:            r,
		serviceOptions: serviceOptions,
		mountPath:      PublicWombatPathPrefix,
		serviceTracer:  serviceOptions.Trace,
		PublicWombat:   svc,
	}
	r.Use(service.serviceTracer.TracingMiddleware("PublicWombat"))
	r.Post("/Echo", service.serveEcho)
	return &service
}

const PublicWombatPathPrefix = "/wombat/v1/public"

// Methods.
func (s *publicWombatService) serveEcho(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = s.serviceTracer.InjectTracer(ctx)
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveEchoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveEchoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		blerr := blaze.ServerInvalidRequestError("Content-Type", msg, req.Method, req.URL.Path)
		blaze.ServerWriteError(ctx, resp, blerr, s.log)
	}
}

func (s *publicWombatService) serveEchoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error

	reqContent := new(wombat_v1_common.EchoMessage)

	respByte, err := io.ReadAll(req.Body)
	if err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorMalformed("the json request could not be decoded"), s.log)
		return
	}
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(respByte, reqContent); err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorMalformed("the json request could not be decoded"), s.log)
		return
	}

	// Call service method
	var respContent *wombat_v1_common.EchoMessage
	func() {
		defer blaze.ServerEnsurePanicResponses(ctx, resp, s.log)
		respContent, err = s.PublicWombat.Echo(ctx, reqContent)
	}()

	if err != nil {
		blaze.ServerWriteError(ctx, resp, err, s.log)
		return
	}
	if respContent == nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorInternal("received a nil response. nil responses are not supported"), s.log)
		return
	}

	var buf []byte
	marshaler := &protojson.MarshalOptions{
		UseProtoNames:   true,
		UseEnumNumbers:  s.serviceOptions.JSONEnumsAsInts,
		EmitUnpopulated: s.serviceOptions.JSONEmitDefaults,
	}
	if buf, err = marshaler.Marshal(respContent); err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorInternalWith(err, "failed to marshal json response"), s.log)
		return
	}

	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(buf)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(buf); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(buf), err.Error())
		blerr := blaze.ErrorInternal(msg)
		s.log.Error(blerr, msg)
	}
}

func (s *publicWombatService) serveEchoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	if err != nil {
		blaze.ServerWriteError(ctx, resp, err, s.log)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorInternalWith(err, "failed to read request body"), s.log)
		return
	}
	reqContent := new(wombat_v1_common.EchoMessage)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorMalformed("the protobuf request could not be decoded"), s.log)
		return
	}

	// Call service method
	var respContent *wombat_v1_common.EchoMessage
	func() {
		defer blaze.ServerEnsurePanicResponses(ctx, resp, s.log)
		respContent, err = s.PublicWombat.Echo(ctx, reqContent)
	}()

	if err != nil {
		blaze.ServerWriteError(ctx, resp, err, s.log)
		return
	}
	if respContent == nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorInternal("received a nil *wombat_v1_common.EchoMessage and nil error while calling Echo. nil responses are not supported"), s.log)
		return
	}

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		blaze.ServerWriteError(ctx, resp, blaze.ErrorInternalWith(err, "failed to marshal proto response"), s.log)
		return
	}

	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		blerr := blaze.ErrorInternal(msg)
		s.log.Error(blerr, msg)
	}
}

func (s *publicWombatService) Mux() *v5.Mux {
	return s.mux
}

func (s *publicWombatService) MountPath() string {
	return s.mountPath
}
